siteTitle="Gatsby Material Starter"
linkPrefix = "/"

userName = "Material User"
userLocation = "Yerevan, Armenia"
userAvatar = "https://api.adorable.io/avatars/150/test.png"
userDescription = "Yeah, I like animals better than people sometimes... Especially dogs. Dogs are the best. Every time you come home, they act like they haven't seen you in a year. And the good thing about dogs... is they got different dogs for different people."

userWebsite = "#"
userGitHub = "#"
userFacebook = "#"
userTwitter = "#"
userInstagram = "#"
userEmail = "#"

copyright = "Copyright Â© 2017. Material User"